openapi: 3.1.0
info:
  title: API with operation tag to be removed
  version: 1.0.0
paths:
  /items:
    get:
      tags:
        - good
        - ugly
      responses:
        200:
          description: OK
