openapi: 3.1.0
info:
  title: API with parameters to be removed
  version: 1.0.0
paths:
  /items:
    get:
      tags:
        - good
        - bad
        - ugly
      parameters:
        - name: filter
          in: query
        - name: dummy
          in: query
      responses:
        200:
          description: OK
