openapi: 3.1.0
info:
  title: API with parameters and tags to be removed
  version: 1.0.0
paths:
  /items:
    get:
      tags:
      - good
      - ugly
      parameters:
      - name: filter
        in: query
      responses:
        200:
          description: OK
