openapi: 3.1.0
info:
  title: API with tags to be updated
  version: 1.0.0
paths:
  /items:
    get:
      tags:
        - good
        - bad
        - special
      responses:
        '200':
          description: OK

