openapi: 3.1.0
info:
  title: API with a paged collection
  version: 1.0.0
paths:
  /items:
    get:
      x-oai-traits:
      - paged
      responses:
        200:
          description: OK
  /items/{id}/subitems:
    get:
      x-oai-traits:
      - paged
      parameters:
      - name: id
        in: path
        required: true
      responses:
        200:
          description: OK
  /other:
    get:
      responses:
        200:
          description: OK
