openapi: 3.1.0
info:
  title: API with a paged collection
  version: 1.0.0
paths:
  /items:
    get:
      x-oai-traits:
        - paged
      responses:
        '200':
          description: OK
      parameters:
        - name: top
          in: query
        - name: skip
          in: query
  /other:
    get:
      responses:
        '200':
          description: OK

