openapi: 3.1.0
info:
  title: API with a paged collection
  version: 1.0.0
paths:
  /items:
    get:
      x-oai-traits:
      - paged
      responses:
        200:
          description: OK
      parameters:
      - &id001
        name: top
        in: query
      - &id002
        name: skip
        in: query
  /items/{id}/subitems:
    get:
      x-oai-traits:
      - paged
      parameters:
      - name: id
        in: path
        required: true
      - *id001
      - *id002
      responses:
        200:
          description: OK
  /other:
    get:
      responses:
        200:
          description: OK
