openapi: 3.1.0
info:
  version: 1.0.0
  title: Imaginary town
paths:
  /locations:
    get:
      summary: All locations
      operationId: locationList
      responses:
        '200':
          description: Returns all locations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    location_id:
                      type: integer
                      example: 44
