openapi: 3.1.0
info:
  title: Simple API
  description: A basic OpenAPI description with a single endpoint.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging.example.com/v1
    description: Staging server
paths: {}
